sudo: required
language: java
matrix:
  include:
  - env: J=Java8
    jdk: oraclejdk8
  - env: J=Java9
    jdk: oraclejdk9
  - env: J=Java10
    jdk: openjdk10
  - env: J=Java11
    jdk: openjdk11

install:
  # first, download all the Maven dependencies without logging
  - mvn -B -q install -DskipTests=true
before_script:
  - PROFILE_OPTS=''
  - case $J in
    Java8) PROFILE_OPTS+='-P sonar' ;;
    Java9) PROFILE_OPTS+='-P sonar' ;;
    Java10) ;;
    Java11) ;;
    esac
script:
  - mvn clean verify $PROFILE_OPTS
addons:
  sonarcloud:
    organization: 'mincong-h-github'
    token: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
