sudo: required
language: java
jdk:
- oraclejdk8
- oraclejdk9
install:
  # first, download all the Maven dependencies without logging
  - mvn -B -q install -DskipTests=true
addons:
  sonarcloud:
    organization: 'mincong-h-github'
    token: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
script:
  - mvn clean verify -P sonar,analyze
