sudo: required
language: java
jdk:
  - oraclejdk8
install:
  # first, download all the Maven dependencies without logging
  - mvn -B -q install -DskipTests=true
addons:
  sonarcloud:
    organization: 'mincong-h-github'
    token: $SONAR_TOKEN
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
